
# .travis.yml
language: ruby
cache: 
  bundler: true
rvm:
  - 2.2.4
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load 
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.example config/database.yml
